import type { Regla } from "./tipos";

export const CAMPOS_CSV = [
  "tipo_documento",
  "numero_documento",
  "numero_seguro_social",
  "nombre",
  "apellido",
  "dias_trabajados",
  "sueldo",
  "horas_extras",
  "decimo_tercer_mes",
  "comisiones",
  "bonificaciones",
  "viaticos",
  "gasto_representacion",
  "primas_produccion",
] as const;

export const TIPOS_DOCUMENTO = ["CEDULA", "PASAPORTE", "CARNE_RESIDENTE"];

export const DICCIONARIO: {
  campo: string;
  grupo: string;
  tipo: string;
  obligatorio: boolean;
  tratamiento: string;
}[] = [
  {
    campo: "tipo_documento",
    grupo: "Identidad",
    tipo: "Catálogo",
    obligatorio: true,
    tratamiento: "Catálogo controlado: CEDULA, PASAPORTE, CARNE_RESIDENTE.",
  },
  {
    campo: "numero_documento",
    grupo: "Identidad",
    tipo: "Texto",
    obligatorio: true,
    tratamiento: "Texto; conserva ceros y guiones. Formato condicionado al tipo de documento.",
  },
  {
    campo: "numero_seguro_social",
    grupo: "Identidad",
    tipo: "Texto",
    obligatorio: true,
    tratamiento: "Correspondencia con la identificación asignada cuando aplique.",
  },
  {
    campo: "nombre",
    grupo: "Identidad",
    tipo: "Texto",
    obligatorio: true,
    tratamiento: "Dato identificador; verificación referencial sujeta a fuente autorizada.",
  },
  {
    campo: "apellido",
    grupo: "Identidad",
    tipo: "Texto",
    obligatorio: true,
    tratamiento: "Dato identificador; verificación referencial sujeta a fuente autorizada.",
  },
  {
    campo: "dias_trabajados",
    grupo: "Consistencia laboral",
    tipo: "Entero",
    obligatorio: true,
    tratamiento: "Tiempo trabajado en el período; entero entre 0 y 30 en la demo.",
  },
  {
    campo: "sueldo",
    grupo: "Remuneración",
    tipo: "Decimal",
    obligatorio: true,
    tratamiento: "Valor monetario; base de consistencia laboral e histórica.",
  },
  {
    campo: "horas_extras",
    grupo: "Remuneración",
    tipo: "Decimal",
    obligatorio: false,
    tratamiento: "Valor monetario; regla salarial documentada.",
  },
  {
    campo: "decimo_tercer_mes",
    grupo: "Remuneración",
    tipo: "Decimal",
    obligatorio: false,
    tratamiento: "Concepto diferenciado del salario ordinario.",
  },
  {
    campo: "comisiones",
    grupo: "Remuneración",
    tipo: "Decimal",
    obligatorio: false,
    tratamiento: "Concepto salarial.",
  },
  {
    campo: "bonificaciones",
    grupo: "Remuneración",
    tipo: "Decimal",
    obligatorio: false,
    tratamiento: "Concepto salarial cuando corresponda según la regla.",
  },
  {
    campo: "viaticos",
    grupo: "Otro rubro",
    tipo: "Decimal",
    obligatorio: false,
    tratamiento: "Tratamiento diferenciado; requiere sustento del gasto.",
  },
  {
    campo: "gasto_representacion",
    grupo: "Remuneración",
    tipo: "Decimal",
    obligatorio: false,
    tratamiento: "Regla salarial específica.",
  },
  {
    campo: "primas_produccion",
    grupo: "Remuneración",
    tipo: "Decimal",
    obligatorio: false,
    tratamiento: "Regla condicional según monto respecto del sueldo.",
  },
];

export const REGLAS: Regla[] = [
  {
    codigo: "REG-EST-001",
    version: "1.0",
    nivel: "A",
    nombre: "Encabezados y esquema del archivo",
    campos: ["archivo"],
    condicion: "El archivo debe contener todas las columnas definidas por la versión del esquema.",
    fuente: "Contrato de datos CSV v1.0",
    fundamento: "Sprint 1 — Contrato funcional de datos",
    resultado: "ERROR",
    accion: "Regenerar el archivo con la plantilla vigente.",
    vigenciaDesde: "2026-01-01",
    estadoRegla: "Activa",
  },
  {
    codigo: "REG-EST-002",
    version: "1.0",
    nivel: "A",
    nombre: "Campo obligatorio presente",
    campos: ["tipo_documento", "numero_documento", "nombre", "apellido", "sueldo"],
    condicion: "Los campos obligatorios no pueden estar vacíos.",
    fuente: "La propia planilla",
    fundamento: "Art. 83 — Registro laboral",
    resultado: "ERROR",
    accion: "Completar el dato faltante y presentar una nueva versión.",
    vigenciaDesde: "2026-01-01",
    estadoRegla: "Activa",
  },
  {
    codigo: "REG-EST-003",
    version: "1.0",
    nivel: "A",
    nombre: "Representación de valores monetarios",
    campos: ["sueldo", "horas_extras", "comisiones", "bonificaciones"],
    condicion: "Los montos deben ser numéricos decimales no negativos.",
    fuente: "Contrato de datos CSV v1.0",
    fundamento: "Sprint 1 — Nivel A, estructura",
    resultado: "ERROR",
    accion: "Corregir el formato del monto (punto decimal, sin símbolos).",
    vigenciaDesde: "2026-01-01",
    estadoRegla: "Activa",
  },
  {
    codigo: "REG-EST-004",
    version: "1.0",
    nivel: "A",
    nombre: "Registro duplicado",
    campos: ["numero_documento", "tipo_documento"],
    condicion: "La combinación tipo + número de documento debe ser única dentro de la planilla.",
    fuente: "La propia planilla",
    fundamento: "CP-03 — Casos de prueba Sprint 1",
    resultado: "ERROR",
    accion: "Eliminar o unificar el registro repetido.",
    vigenciaDesde: "2026-01-01",
    estadoRegla: "Activa",
  },
  {
    codigo: "REG-IDE-001",
    version: "1.0",
    nivel: "B",
    nombre: "Tipo de documento dentro del catálogo",
    campos: ["tipo_documento"],
    condicion: "El valor debe pertenecer al catálogo controlado.",
    fuente: "Catálogo local de la plataforma",
    fundamento: "Art. 83 — Identificación del trabajador",
    resultado: "ERROR",
    accion: "Seleccionar un tipo de documento válido.",
    vigenciaDesde: "2026-01-01",
    estadoRegla: "Activa",
  },
  {
    codigo: "REG-IDE-002",
    version: "1.0",
    nivel: "B",
    nombre: "Formato del número de documento según tipo",
    campos: ["numero_documento"],
    condicion:
      "CEDULA: patrón n-nnnn-nnnn. PASAPORTE: 6 a 12 alfanuméricos. CARNE_RESIDENTE: 6 a 12 alfanuméricos.",
    fuente: "La propia planilla",
    fundamento: "CP-02 — Casos de prueba Sprint 1",
    resultado: "ERROR",
    accion: "Corregir el número según el formato del tipo de documento.",
    vigenciaDesde: "2026-01-01",
    estadoRegla: "Activa",
  },
  {
    codigo: "REG-IDE-003",
    version: "1.0",
    nivel: "B",
    nombre: "Número de seguro social presente y coherente",
    campos: ["numero_seguro_social"],
    condicion: "Debe tener entre 6 y 14 caracteres alfanuméricos cuando el trabajador ya está asegurado.",
    fuente: "La propia planilla (validación local)",
    fundamento: "Art. 83 — Registro laboral",
    resultado: "ALERTA",
    accion: "Confirmar el número asignado o justificar su ausencia.",
    vigenciaDesde: "2026-01-01",
    estadoRegla: "Limitada",
  },
  {
    codigo: "REG-IDE-004",
    version: "1.0",
    nivel: "B",
    nombre: "Verificación referencial contra fuente institucional",
    campos: ["nombre", "apellido", "numero_seguro_social"],
    condicion: "Comparación con fuentes oficiales autorizadas cuando exista integración formal.",
    fuente: "Fuente institucional (no disponible en la demo)",
    fundamento: "Sprint 1 — Nivel B, validación institucional",
    resultado: "ALERTA",
    accion: "Regla declarada pendiente: no se simula la verificación institucional.",
    vigenciaDesde: "2026-01-01",
    estadoRegla: "Pendiente de validación institucional",
  },
  {
    codigo: "REG-LAB-001",
    version: "1.0",
    nivel: "C",
    nombre: "Días trabajados dentro del período",
    campos: ["dias_trabajados"],
    condicion: "Entero entre 0 y 30 para un período mensual.",
    fuente: "La propia planilla",
    fundamento: "Art. 83 — Tiempo trabajado",
    resultado: "ERROR",
    accion: "Corregir el tiempo trabajado declarado en el período.",
    vigenciaDesde: "2026-01-01",
    estadoRegla: "Activa",
  },
  {
    codigo: "REG-LAB-002",
    version: "1.0",
    nivel: "C",
    nombre: "Sueldo declarado en cero con días trabajados",
    campos: ["sueldo", "dias_trabajados"],
    condicion: "Si hay días trabajados mayores a cero, el sueldo no debe ser cero.",
    fuente: "La propia planilla",
    fundamento: "Art. 85 — Concepto de salario",
    resultado: "ERROR",
    accion: "Registrar el salario devengado o corregir los días trabajados.",
    vigenciaDesde: "2026-01-01",
    estadoRegla: "Activa",
  },
  {
    codigo: "REG-CON-001",
    version: "1.0",
    nivel: "D",
    nombre: "Rubro declarado sin sueldo asociado",
    campos: ["comisiones", "bonificaciones", "horas_extras"],
    condicion: "Un rubro remunerativo no debe declararse cuando no existe sueldo ni días trabajados.",
    fuente: "La propia planilla",
    fundamento: "Sprint 1 — Nivel D, consistencia entre campos",
    resultado: "ERROR",
    accion: "Revisar la relación entre el rubro declarado y el salario del período.",
    vigenciaDesde: "2026-01-01",
    estadoRegla: "Activa",
  },
  {
    codigo: "REG-CON-002",
    version: "1.0",
    nivel: "D",
    nombre: "Horas extras desproporcionadas respecto del sueldo",
    campos: ["horas_extras", "sueldo"],
    condicion: "Horas extras superiores al 100% del sueldo del período requieren revisión.",
    fuente: "La propia planilla",
    fundamento: "Umbral configurable de la plataforma (no normativo)",
    resultado: "ALERTA",
    accion: "Confirmar o justificar el monto declarado.",
    vigenciaDesde: "2026-01-01",
    estadoRegla: "Activa",
  },
  {
    codigo: "REG-SAL-001",
    version: "1.0",
    nivel: "E",
    nombre: "Viáticos con tratamiento diferenciado",
    campos: ["viaticos"],
    condicion:
      "Viáticos superiores al 25% del sueldo requieren revisión del sustento; no se clasifican automáticamente como salario.",
    fuente: "La propia planilla",
    fundamento: "Art. 86 — Excepciones y tratamientos diferenciados",
    resultado: "ALERTA",
    accion: "Adjuntar o confirmar el sustento del gasto reembolsable.",
    vigenciaDesde: "2026-01-01",
    estadoRegla: "Activa",
  },
  {
    codigo: "REG-SAL-002",
    version: "1.0",
    nivel: "E",
    nombre: "Gasto de representación mayor al sueldo",
    campos: ["gasto_representacion", "sueldo"],
    condicion: "Gasto de representación superior al sueldo ordinario requiere revisión de la clasificación.",
    fuente: "La propia planilla",
    fundamento: "Art. 85 y 86 — Salario y excepciones",
    resultado: "ALERTA",
    accion: "Revisar la clasificación del rubro según la regla aplicable.",
    vigenciaDesde: "2026-01-01",
    estadoRegla: "Activa",
  },
  {
    codigo: "REG-SAL-003",
    version: "2026.1",
    nivel: "E",
    nombre: "Sueldo por debajo del salario mínimo legal vigente",
    campos: ["sueldo", "dias_trabajados"],
    condicion:
      "El sueldo del período, prorrateado por días trabajados, se compara con la tasa por hora que fija el Decreto Ejecutivo 13 de 2025 para la actividad, el tamaño de empresa y la región del empleador (jornada de referencia de 48 horas semanales).",
    fuente: "Decreto Ejecutivo N.° 13 de 31 de diciembre de 2025 (MITRADEL) — Gaceta Oficial 30438",
    fundamento: "Salario mínimo vigente desde el 16 de enero de 2026, por actividad y región",
    resultado: "ERROR",
    accion:
      "Verificar la clasificación de actividad, tamaño y región, y ajustar el sueldo a la tasa mínima aplicable.",
    vigenciaDesde: "2026-01-16",
    estadoRegla: "Activa",
  },
  {
    codigo: "REG-SAL-005",
    version: "1.0",
    nivel: "E",
    nombre: "Prima de producción condicionada al monto",
    campos: ["primas_produccion", "sueldo"],
    condicion:
      "La prima de producción se evalúa según su proporción respecto del sueldo mensual; el umbral definitivo requiere validación institucional.",
    fuente: "La propia planilla",
    fundamento: "Art. 85 y 86 — pendiente de reglamentación aplicable",
    resultado: "ALERTA",
    accion: "Revisar la clasificación con el área competente antes de continuar.",
    vigenciaDesde: "2026-01-01",
    estadoRegla: "Pendiente de validación institucional",
  },
  {
    codigo: "REG-HIS-001",
    version: "1.0",
    nivel: "F",
    nombre: "Variación atípica de sueldo entre períodos",
    campos: ["sueldo"],
    condicion:
      "Variación superior al 40% respecto del período anterior del mismo trabajador (umbral configurable).",
    fuente: "Historial de planillas del mismo empleador",
    fundamento: "CP-05 — Casos de prueba Sprint 1",
    resultado: "ALERTA",
    accion: "Confirmar el cambio o adjuntar el movimiento laboral que lo explica.",
    vigenciaDesde: "2026-01-01",
    estadoRegla: "Activa",
  },
  {
    codigo: "REG-HIS-002",
    version: "1.0",
    nivel: "F",
    nombre: "Trabajador ausente respecto del período anterior",
    campos: ["numero_documento"],
    condicion: "El trabajador presente en el período anterior no aparece en el período actual.",
    fuente: "Historial de planillas del mismo empleador",
    fundamento: "CP-06 — Casos de prueba Sprint 1",
    resultado: "ALERTA",
    accion: "Confirmar la baja o incorporar al trabajador omitido.",
    vigenciaDesde: "2026-01-01",
    estadoRegla: "Activa",
  },
  {
    codigo: "REG-HIS-003",
    version: "1.0",
    nivel: "F",
    nombre: "Trabajador nuevo respecto del período anterior",
    campos: ["numero_documento"],
    condicion: "El trabajador no figuraba en el período anterior del mismo empleador.",
    fuente: "Historial de planillas del mismo empleador",
    fundamento: "Sprint 1 — Nivel F, revisión histórica",
    resultado: "ALERTA",
    accion: "Confirmar el ingreso registrado en el período.",
    vigenciaDesde: "2026-01-01",
    estadoRegla: "Activa",
  },
];

export const NIVELES: { nivel: string; titulo: string; objetivo: string }[] = [
  {
    nivel: "A",
    titulo: "Estructura",
    objetivo:
      "Determina si la información puede interpretarse: campos, tipos, formatos, vacíos, montos y duplicados.",
  },
  {
    nivel: "B",
    titulo: "Identidad",
    objetivo:
      "Coherencia entre tipo y número de documento, número de seguro social, nombre y apellido.",
  },
  {
    nivel: "C",
    titulo: "Consistencia laboral",
    objetivo: "Relaciona trabajador, empleador, período, tiempo trabajado, sueldo y rubros.",
  },
  {
    nivel: "D",
    titulo: "Consistencia entre campos",
    objetivo: "Busca contradicciones o dependencias incumplidas dentro de la misma planilla.",
  },
  {
    nivel: "E",
    titulo: "Validación normativa de rubros",
    objetivo: "Aplica reglas sobre salario y sus tratamientos diferenciados, campo por campo.",
  },
  {
    nivel: "F",
    titulo: "Revisión histórica",
    objetivo: "Compara períodos para identificar variaciones que requieran confirmación humana.",
  },
];

export const MATRIZ_NORMATIVA: { norma: string; tema: string; aplicacion: string; reglas: string[] }[] = [
  {
    norma: "Ley 51 de 2005 + Texto Único 2025 — Art. 83",
    tema: "Registro laboral",
    aplicacion: "Identidad del trabajador, tiempo trabajado, períodos y salarios devengados.",
    reglas: ["REG-EST-002", "REG-IDE-001", "REG-IDE-003", "REG-LAB-001"],
  },
  {
    norma: "Texto Único Ley 51 — Art. 85",
    tema: "Concepto de salario",
    aplicacion: "Base para clasificar remuneraciones que forman parte del salario.",
    reglas: ["REG-LAB-002", "REG-SAL-002", "REG-SAL-005"],
  },
  {
    norma: "Texto Único Ley 51 — Art. 86",
    tema: "Excepciones y tratamientos diferenciados",
    aplicacion: "Evita clasificar automáticamente todos los rubros como salario.",
    reglas: ["REG-SAL-001", "REG-SAL-002", "REG-SAL-005"],
  },
  {
    norma: "Texto Único Ley 51 — Art. 87",
    tema: "Recepción, validación y corrección",
    aplicacion: "Sustenta los controles de exactitud, el versionado y la corrección.",
    reglas: ["REG-EST-001", "REG-EST-004"],
  },
  {
    norma: "Texto Único Ley 51 — Art. 119",
    tema: "Declaraciones falsas, subdeclaración u omisión",
    aplicacion:
      "Contexto jurídico: la plataforma genera alertas para revisión humana y no califica infracciones.",
    reglas: ["REG-HIS-001", "REG-HIS-002"],
  },
  {
    norma: "Texto Único Ley 51 — Art. 121",
    tema: "Mora",
    aplicacion: "Consecuencia legal contextual; sin cálculo automático dentro del alcance del MVP.",
    reglas: [],
  },
  {
    norma: "Ley 81 de 2019 y Decreto Ejecutivo 285 de 2021",
    tema: "Protección de datos personales",
    aplicacion: "Minimización, datos sintéticos en pruebas y control de acceso por empleador.",
    reglas: [],
  },
  {
    norma: "Ley 51 de 2008, Ley 82 y 83 de 2012, Ley 144 de 2020",
    tema: "Documentos electrónicos y trámites digitales",
    aplicacion: "Marco para evidencia electrónica; la firma electrónica queda fuera del MVP.",
    reglas: [],
  },
  {
    norma: "Lineamientos AIG 2026",
    tema: "Ciberseguridad para entidades públicas",
    aplicacion: "Referencia para controles de seguridad, registro de eventos y hardening de ambientes.",
    reglas: [],
  },
];

export const CASOS_PRUEBA = [
  { caso: "CP-01", condicion: "Falta un identificador obligatorio", esperado: "Error bloqueante", regla: "REG-EST-002" },
  { caso: "CP-02", condicion: "Documento con formato inválido", esperado: "Error bloqueante", regla: "REG-IDE-002" },
  { caso: "CP-03", condicion: "Registro duplicado", esperado: "Error bloqueante", regla: "REG-EST-004" },
  { caso: "CP-04", condicion: "Todos los datos cumplen", esperado: "Válido", regla: "—" },
  { caso: "CP-05", condicion: "Salario cambia de forma atípica", esperado: "Alerta", regla: "REG-HIS-001" },
  { caso: "CP-06", condicion: "Trabajador desaparece respecto al período anterior", esperado: "Alerta", regla: "REG-HIS-002" },
  { caso: "CP-07", condicion: "Viático con tratamiento incompatible", esperado: "Resultado según regla", regla: "REG-SAL-001" },
  { caso: "CP-08", condicion: "Prima de producción", esperado: "Evaluar condición documentada", regla: "REG-SAL-005" },
  { caso: "CP-09", condicion: "Usuario de empresa A consulta empresa B", esperado: "Acceso denegado", regla: "Control de acceso" },
  { caso: "CP-10", condicion: "Se reenvía exactamente la misma solicitud", esperado: "No duplicar procesamiento", regla: "Idempotencia" },
  { caso: "CP-11", condicion: "Se envía una versión corregida", esperado: "Conservar ambas versiones", regla: "Versionado" },
  { caso: "CP-12", condicion: "Cambia una regla normativa", esperado: "Aplicar según vigencia", regla: "Vigencia de reglas" },
];
