/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArquitecturaRouteImport } from './routes/arquitectura'
import { Route as DiagramaRouteImport } from './routes/diagrama'
import { Route as EquipoRouteImport } from './routes/equipo'
import { Route as InstalarHerramientasRouteImport } from './routes/instalar-herramientas'
import { Route as NormativaRouteImport } from './routes/normativa'
import { Route as ReglasRouteImport } from './routes/reglas'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as DemoAuditoriaRouteImport } from './routes/demo/auditoria'
import { Route as DemoCargarRouteImport } from './routes/demo/cargar'
import { Route as DemoErroresRouteImport } from './routes/demo/errores'
import { Route as DemoReferenciaRouteImport } from './routes/demo/referencia'
import { Route as DemoPlanillasIndexRouteImport } from './routes/demo/planillas.index'
import { Route as DemoPlanillasPlanillaIdRouteImport } from './routes/demo/planillas.$planillaId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArquitecturaRoute = ArquitecturaRouteImport.update({
  id: '/arquitectura',
  path: '/arquitectura',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagramaRoute = DiagramaRouteImport.update({
  id: '/diagrama',
  path: '/diagrama',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoRoute = EquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => rootRouteImport,
} as any)
const InstalarHerramientasRoute = InstalarHerramientasRouteImport.update({
  id: '/instalar-herramientas',
  path: '/instalar-herramientas',
  getParentRoute: () => rootRouteImport,
} as any)
const NormativaRoute = NormativaRouteImport.update({
  id: '/normativa',
  path: '/normativa',
  getParentRoute: () => rootRouteImport,
} as any)
const ReglasRoute = ReglasRouteImport.update({
  id: '/reglas',
  path: '/reglas',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAuditoriaRoute = DemoAuditoriaRouteImport.update({
  id: '/demo/auditoria',
  path: '/demo/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoCargarRoute = DemoCargarRouteImport.update({
  id: '/demo/cargar',
  path: '/demo/cargar',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoErroresRoute = DemoErroresRouteImport.update({
  id: '/demo/errores',
  path: '/demo/errores',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoReferenciaRoute = DemoReferenciaRouteImport.update({
  id: '/demo/referencia',
  path: '/demo/referencia',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPlanillasIndexRoute = DemoPlanillasIndexRouteImport.update({
  id: '/demo/planillas/',
  path: '/demo/planillas/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPlanillasPlanillaIdRoute = DemoPlanillasPlanillaIdRouteImport.update({
  id: '/demo/planillas/$planillaId',
  path: '/demo/planillas/$planillaId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arquitectura': typeof ArquitecturaRoute
  '/diagrama': typeof DiagramaRoute
  '/equipo': typeof EquipoRoute
  '/instalar-herramientas': typeof InstalarHerramientasRoute
  '/normativa': typeof NormativaRoute
  '/reglas': typeof ReglasRoute
  '/tutorial': typeof TutorialRoute
  '/demo/auditoria': typeof DemoAuditoriaRoute
  '/demo/cargar': typeof DemoCargarRoute
  '/demo/errores': typeof DemoErroresRoute
  '/demo/referencia': typeof DemoReferenciaRoute
  '/demo/': typeof DemoIndexRoute
  '/demo/planillas/$planillaId': typeof DemoPlanillasPlanillaIdRoute
  '/demo/planillas/': typeof DemoPlanillasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arquitectura': typeof ArquitecturaRoute
  '/diagrama': typeof DiagramaRoute
  '/equipo': typeof EquipoRoute
  '/instalar-herramientas': typeof InstalarHerramientasRoute
  '/normativa': typeof NormativaRoute
  '/reglas': typeof ReglasRoute
  '/tutorial': typeof TutorialRoute
  '/demo/auditoria': typeof DemoAuditoriaRoute
  '/demo/cargar': typeof DemoCargarRoute
  '/demo/errores': typeof DemoErroresRoute
  '/demo/referencia': typeof DemoReferenciaRoute
  '/demo': typeof DemoIndexRoute
  '/demo/planillas/$planillaId': typeof DemoPlanillasPlanillaIdRoute
  '/demo/planillas': typeof DemoPlanillasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arquitectura': typeof ArquitecturaRoute
  '/diagrama': typeof DiagramaRoute
  '/equipo': typeof EquipoRoute
  '/instalar-herramientas': typeof InstalarHerramientasRoute
  '/normativa': typeof NormativaRoute
  '/reglas': typeof ReglasRoute
  '/tutorial': typeof TutorialRoute
  '/demo/auditoria': typeof DemoAuditoriaRoute
  '/demo/cargar': typeof DemoCargarRoute
  '/demo/errores': typeof DemoErroresRoute
  '/demo/referencia': typeof DemoReferenciaRoute
  '/demo/': typeof DemoIndexRoute
  '/demo/planillas/$planillaId': typeof DemoPlanillasPlanillaIdRoute
  '/demo/planillas/': typeof DemoPlanillasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arquitectura'
    | '/diagrama'
    | '/equipo'
    | '/instalar-herramientas'
    | '/normativa'
    | '/reglas'
    | '/tutorial'
    | '/demo/auditoria'
    | '/demo/cargar'
    | '/demo/errores'
    | '/demo/referencia'
    | '/demo/'
    | '/demo/planillas/$planillaId'
    | '/demo/planillas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arquitectura'
    | '/diagrama'
    | '/equipo'
    | '/instalar-herramientas'
    | '/normativa'
    | '/reglas'
    | '/tutorial'
    | '/demo/auditoria'
    | '/demo/cargar'
    | '/demo/errores'
    | '/demo/referencia'
    | '/demo'
    | '/demo/planillas/$planillaId'
    | '/demo/planillas'
  id:
    | '__root__'
    | '/'
    | '/arquitectura'
    | '/diagrama'
    | '/equipo'
    | '/instalar-herramientas'
    | '/normativa'
    | '/reglas'
    | '/tutorial'
    | '/demo/auditoria'
    | '/demo/cargar'
    | '/demo/errores'
    | '/demo/referencia'
    | '/demo/'
    | '/demo/planillas/$planillaId'
    | '/demo/planillas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArquitecturaRoute: typeof ArquitecturaRoute
  DiagramaRoute: typeof DiagramaRoute
  EquipoRoute: typeof EquipoRoute
  InstalarHerramientasRoute: typeof InstalarHerramientasRoute
  NormativaRoute: typeof NormativaRoute
  ReglasRoute: typeof ReglasRoute
  TutorialRoute: typeof TutorialRoute
  DemoAuditoriaRoute: typeof DemoAuditoriaRoute
  DemoCargarRoute: typeof DemoCargarRoute
  DemoErroresRoute: typeof DemoErroresRoute
  DemoReferenciaRoute: typeof DemoReferenciaRoute
  DemoIndexRoute: typeof DemoIndexRoute
  DemoPlanillasPlanillaIdRoute: typeof DemoPlanillasPlanillaIdRoute
  DemoPlanillasIndexRoute: typeof DemoPlanillasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arquitectura': {
      id: '/arquitectura'
      path: '/arquitectura'
      fullPath: '/arquitectura'
      preLoaderRoute: typeof ArquitecturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagrama': {
      id: '/diagrama'
      path: '/diagrama'
      fullPath: '/diagrama'
      preLoaderRoute: typeof DiagramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo': {
      id: '/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof EquipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instalar-herramientas': {
      id: '/instalar-herramientas'
      path: '/instalar-herramientas'
      fullPath: '/instalar-herramientas'
      preLoaderRoute: typeof InstalarHerramientasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/normativa': {
      id: '/normativa'
      path: '/normativa'
      fullPath: '/normativa'
      preLoaderRoute: typeof NormativaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reglas': {
      id: '/reglas'
      path: '/reglas'
      fullPath: '/reglas'
      preLoaderRoute: typeof ReglasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/demo'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/auditoria': {
      id: '/demo/auditoria'
      path: '/demo/auditoria'
      fullPath: '/demo/auditoria'
      preLoaderRoute: typeof DemoAuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/cargar': {
      id: '/demo/cargar'
      path: '/demo/cargar'
      fullPath: '/demo/cargar'
      preLoaderRoute: typeof DemoCargarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/errores': {
      id: '/demo/errores'
      path: '/demo/errores'
      fullPath: '/demo/errores'
      preLoaderRoute: typeof DemoErroresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/referencia': {
      id: '/demo/referencia'
      path: '/demo/referencia'
      fullPath: '/demo/referencia'
      preLoaderRoute: typeof DemoReferenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/planillas/': {
      id: '/demo/planillas/'
      path: '/demo/planillas'
      fullPath: '/demo/planillas/'
      preLoaderRoute: typeof DemoPlanillasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/planillas/$planillaId': {
      id: '/demo/planillas/$planillaId'
      path: '/demo/planillas/$planillaId'
      fullPath: '/demo/planillas/$planillaId'
      preLoaderRoute: typeof DemoPlanillasPlanillaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArquitecturaRoute: ArquitecturaRoute,
  DiagramaRoute: DiagramaRoute,
  EquipoRoute: EquipoRoute,
  InstalarHerramientasRoute: InstalarHerramientasRoute,
  NormativaRoute: NormativaRoute,
  ReglasRoute: ReglasRoute,
  TutorialRoute: TutorialRoute,
  DemoAuditoriaRoute: DemoAuditoriaRoute,
  DemoCargarRoute: DemoCargarRoute,
  DemoErroresRoute: DemoErroresRoute,
  DemoReferenciaRoute: DemoReferenciaRoute,
  DemoIndexRoute: DemoIndexRoute,
  DemoPlanillasPlanillaIdRoute: DemoPlanillasPlanillaIdRoute,
  DemoPlanillasIndexRoute: DemoPlanillasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
